---
title: Avoid UNDEFINED values in author fields
category: fixed
author: Quan Zhou <quan@bitergia.com>
issue: null
notes: >
    Avoid `-- UNDEFINED --` values for all SortingHat fields when
    Mordred loses connection to the SortingHat server during the
    enrichment or autorefresh execution. It will keep the values
    of the `name`, `email`, `id` and `uuid` fields.
